//! Bindings for the packagekit dbus interface generated by zbus_xmlgen
//! v5.5.0. Packagekit is stable so it should't be necessarry to update
//! this crate, but if you do, please note that you need to disable the
//! event buffer size limit in quick_xml. The simplest way of doing this is
//! probably to make a custom build of zbus_xmlgen and removing any calls to
//! `Deserializer::event_buffer_size`.
pub mod offline;
pub mod package_kit;
pub mod transaction;
