[package]
name = "ladybug"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
toml = "0.5.8"
serde = {version = "1.0", features = ["derive"]}
tera = "1.12.1"
directories-next = "2.0.0"
anyhow = "1.0"
ignore = "0.4.18"
