[package]
name = "ladybug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.0.13", features = ["derive", "color"]}
toml = "0.5.8"
serde = {version = "1.0.136", features = ["derive"]}
tera = "1.15.0"
directories-next = "2.0.0"
anyhow = "1.0.53"
globwalk = "0.8.1"
figment = {version = "0.10.6", features = ["toml"]}
log = "0.4.14"
env_logger = "0.9.0"

[dev-dependencies]
tempfile = "3.3.0"
