theme = "onedark"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[editor.lsp]
display-signature-help-docs = false

[keys.normal]
H = "goto_first_nonwhitespace"
L = "goto_line_end"
"C-s" = ":write"
c = ["trim_selections", "change_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]      
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = { k = "normal_mode" }

[keys.select]
H = "goto_first_nonwhitespace"
L = "goto_line_end"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
